name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v6

      - name: 设置 Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x

      - name: 发布到 JSR
        run: deno publish
